### ISSUE TITLE
Test load on Renku deployments

### ISSUE THREAD

**Issue by pameladelgado** [SwissDataScienceCenter/renku-demo#24]
Following SV demo of 13.12.2018 on renkulab.io that made the gateway fail. Try to reproduce the problem if possible.
Check: https://github.com/SwissDataScienceCenter/renku/blob/master/tests/test_renku.py#L41

**Comment by fgeorgatos** [comment]
and here's the load testing tool i was mentioning this morning, 
you're probably one button away under rancher to install it via the catalog:
* https://rancher.renku.ch/p/c-2nn99:p-59vpk/apps/catalog/helm-locust ## this is SV, example only

**Comment by rokroskar** [comment]
I think this has been mostly fixed with the new gateway release. I will make a separate issue to document how to use locust and provide a sample locustfile.
